{
 "title": "Minikube",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Running Pod Count:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"celery-flask-deployment-.*\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage as % of Request:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod=~\"celery-flask-deployment-.*\"}) by (pod) / 629145600) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage as % of Request:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{pod=~\"celery-flask-deployment-.*\"}[5m])) by (pod) / 0.45) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"celery-flask-deployment-.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "milicore" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"celery-flask-deployment-.*\"}[5m])) by (pod) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}