apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flask-deployment
  labels:
    app: celery-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-flask-app
  template:
    metadata:
      labels:
        app: celery-flask-app
    spec:
      containers:
      - name: celery-flask-container
        image: my-celery-flask-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "your-access-key-id"
        - name: AWS_SECRET_ACCESS_KEY
          value: "your-secret-access-key"
        - name: AWS_DEFAULT_REGION
          value: "us-east-2"
        resources:
          requests:
            cpu: "450m"
            memory: "600Mi"
          limits:
            cpu: "600m"
            memory: "750Mi"
        volumeMounts:
        - name: celery-results-storage
          mountPath: /app/celery-results
      volumes:
      - name: celery-results-storage
        persistentVolumeClaim:
          claimName: celery-results-pvc
