apiVersion: v1
kind: Service
metadata:
  name: celery-flask-service
spec:
  type: NodePort
  selector:
    app: celery-flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
